# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.service import Service as FirefoxService

class TestTestCase3():
  def setup_method(self, method):
    browser_name = "firefox"

    if browser_name == "chrome":
      chrome_driver_binary = r'.\drivers\chromedriver'
      self.driver = webdriver.Chrome(chrome_driver_binary)
      self.vars = {}
    elif browser_name == "firefox":
      firefox_driver_binary = r'.\drivers\geckodriver'
      ser_firefox = FirefoxService(firefox_driver_binary)
      self.driver = webdriver.Firefox(service=ser_firefox)
    else:
      edge_driver_binary = r'.\drivers\msedgedriver'
      self.driver = webdriver.Edge(edge_driver_binary)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCase3(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "register").click()
    self.driver.find_element(By.ID, "firstname").click()
    self.driver.find_element(By.ID, "lastname").click()
    self.driver.find_element(By.ID, "Email").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wrapperConsolidator").click()
    first_name_error_msg=self.driver.find_element(By.CSS_SELECTOR,"#firstname_err")
    last_name_error_msg=self.driver.find_element(By.CSS_SELECTOR,"#lastname_err")
    email_error_msg=self.driver.find_element(By.CSS_SELECTOR,"#Email_err")
    password_error_msg=self.driver.find_element(By.CSS_SELECTOR,"#password_err")
    assert "Please enter your first name"==first_name_error_msg.text
    assert "Please enter your last name" == last_name_error_msg.text
    assert "Please enter your email address." == email_error_msg.text
    assert "Please enter a password." == password_error_msg.text




