# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.common import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.service import Service as FirefoxService

import test_testCase4


class TestPositive():
  def setup_method(self, method):
      browser_name = "edge"

      if browser_name == "chrome":
          chrome_driver_binary = r'.\drivers\chromedriver'
          self.driver = webdriver.Chrome(chrome_driver_binary)
          self.vars = {}
      elif browser_name == "firefox":
          firefox_driver_binary = r'.\drivers\geckodriver'
          ser_firefox = FirefoxService(firefox_driver_binary)
          self.driver = webdriver.Firefox(service=ser_firefox)
      else:
          edge_driver_binary = r'.\drivers\msedgedriver'
          self.driver = webdriver.Edge(edge_driver_binary)


  def teardown_method(self, method):
    self.driver.quit()
  
  def test_positive(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "create-account-link").click()
    self.driver.find_element(By.ID, "firstname").click()
    name="john"
    self.driver.find_element(By.ID, "firstname").send_keys(name)
    self.driver.find_element(By.ID, "lastname").send_keys("she")
    self.driver.find_element(By.ID, "Email").send_keys("xipax97816@runqx.com")
    self.driver.find_element(By.ID, "password").send_keys("991594123rossffffdo")
    time.sleep(5)
    self.driver.find_element(By.ID, "EMAIL_REG_FORM_SUBMIT").click()

    try:
       time.sleep(5)
       profile_name=self.driver.find_element(By.CSS_SELECTOR,"b:nth-child(1)").text
       time.sleep(5)
       assert name==profile_name
    except NoSuchElementException:
      print("\nno such element")
  
