# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


def float_price(str1: str):
  new_str = ""
  for i in str1:
    if i.isdigit() or i == ".":
      new_str += i
  num = float(new_str)
  return num


class TestTest3():
  def setup_method(self, method):
    chrome_driver_binary = r'.\drivers\chromedriver'
    self.driver = webdriver.Chrome(chrome_driver_binary)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()


  def test_case3333(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").send_keys("firecak226@serosin.com")
    time.sleep(3)
    self.driver.find_element(By.ID, "signin-continue-btn").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "pass").send_keys("991594123rami")
    time.sleep(3)
    # self.driver.find_element(By.ID, "sgnBt").click()
    element = self.driver.find_element(By.ID, "sgnBt")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    element.send_keys(Keys.ENTER)
    time.sleep(5)
    element = self.driver.find_element(By.CSS_SELECTOR, "#mainContent > div.hl-cat-nav > ul > li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Apple").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR,"#mainContent > section.b-module.b-visualnav > div.b-visualnav__grid > a:nth-child(1) > div.b-visualnav__img.b-visualnav__img__default > img").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR,"#s0-28-9-0-1\[1\]-0-0-12-list > li:nth-child(2) > a > div.b-tile__imgwrap > div > img").click()





  def test_test3(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").send_keys("firecak226@serosin.com")
    time.sleep(3)
    self.driver.find_element(By.ID, "signin-continue-btn").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "pass").send_keys("991594123rami")
    time.sleep(3)
    # self.driver.find_element(By.ID, "sgnBt").click()
    element = self.driver.find_element(By.ID, "sgnBt")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    element.send_keys(Keys.ENTER)
    time.sleep(5)
    element = self.driver.find_element(By.CSS_SELECTOR, "#mainContent > div.hl-cat-nav > ul > li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Apple").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".b-visualnav__tile:nth-child(1) .b-img").click()
    time.sleep(5)
    element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img").click()
    # time.sleep(8)
    # self.driver.find_element(By.CSS_SELECTOR, "#s0-28-9-0-1\[1\]-0-0-12-list > li:nth-child(1) > a > div.b-info > div.b-info__title").click()
    # self.driver.find_element(By.XPATH,'"//*[@id="s0-28-9-0-1[1]-0-0-12-list"]/li[1]/a/div[1]/div/img"').click()
    time.sleep(5)
    self.driver.find_element(By.ID, "isCartBtn_btn").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "s0-0-20-10-11-electro-wireless-1346549252-144195215991-qty[]-1-dropdown").click()
    dropdown = self.driver.find_element(By.ID, "s0-0-20-10-11-electro-wireless-1346549252-144195215991-qty[]-1-dropdown")
    time.sleep(3)
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    time.sleep(3)
    price_unit=self.driver.find_element(By.CSS_SELECTOR,"#mainContent > div > div.right-section > div > div.table > div:nth-child(1) > div.val-col > span > span > span").text
    pu=float_price(price_unit)
    price_shipping=self.driver.find_element(By.CSS_SELECTOR,"#mainContent > div > div.right-section > div > div.table > div:nth-child(2) > div.val-col > span > span > span").text
    psh=float_price(price_shipping)
    price_import=self.driver.find_element(By.CSS_SELECTOR,"#mainContent > div > div.right-section > div > div.table > div:nth-child(3) > div.val-col > span > span > span").text
    pi=float_price(price_import)
    total_price=self.driver.find_element(By.CSS_SELECTOR,"#mainContent > div > div.right-section > div > div.table > div:nth-child(5) > div.val-col.total-row > span > span > span").text
    total=float_price(total_price)
    time.sleep(5)
    res=pu+psh+pi
    assert total==res

